name: Release

on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  pull-requests: write
jobs:
  release-npm:
    name: Release NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - name: Install and test
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          bun install --frozen-lockfile
          bun run test
      - name: Version bump and create pull request OR publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun run publish
          commit: 🚀 Release
          title: 🚀 Release
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
